# Generated by Django 2.2.4 on 2019-08-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0002_auto_20190813_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=True, to='rbac.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详细')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, '未处理'), (2, '处理中'), (3, '已处理')], default=1)),
                ('solution', models.TextField(blank=True, null=True)),
                ('ptime', models.DateTimeField(blank=True, null=True)),
                ('create_user', models.ForeignKey(on_delete=True, related_name='aaa', to='web.UserInfo')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=True, related_name='bbb', to='web.UserInfo')),
            ],
        ),
    ]
